# fly.toml app configuration file generated for etbcor on 2023-08-16T11:19:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "etbcor"
primary_region = "phx"

[build]
image = "etbcor/personal-site:latest"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
